## Importing NumPy

In [4]:
import numpy as np

---

# 1. DataTypes & Attributes

In [5]:
# NumPy's main datatype is ndarray (n dimensional array)
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [6]:
type(arr1)

numpy.ndarray

***

In [7]:
arr2 = np.array([[1, 2.0, 3.3], 
                 [4, 5, 6.5]])

arr3 = np.array([[[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]], 
                 [[10, 11, 12], 
                  [13, 14, 15], 
                  [16, 17, 18]]])

In [8]:
arr2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

![](images/anatomy-of-a-numpy-array.png)

1. If an array is 1D array, we can call it 'Vector'
2. If an array is more than 1D array, we can call it 'Matrix'

---

### Shapes of the arrays

In [13]:
arr1.shape

(3,)

In [14]:
arr2.shape

(2, 3)

In [15]:
arr3.shape

(2, 3, 3)

### Dimensions of the arrays

In [16]:
arr1.ndim

1

In [17]:
arr2.ndim

2

In [18]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

### Data types of the arrays

In [19]:
arr1.dtype

dtype('int32')

In [20]:
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

### Sizes of the arrays (Elements count)

In [21]:
arr1.size, arr2.size, arr3.size

(3, 6, 18)

### Types of the arrays

In [22]:
type(arr1), type(arr2), type(arr3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

---

# 2. Create a DataFrame from a NumPy array

In [25]:
import pandas as pd

df = pd.DataFrame(arr2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [27]:
# df2 = pd.DataFrame(arr3)
# df2           # Error Occurs => ValueError: Must pass 2-d input. shape=(2, 3, 3)

---

# 3. Creating Arrays

In [30]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [31]:
sample_array.dtype

dtype('int32')

In [35]:
ones = np.ones((2, 3))
ones

# press "shift + tab" to see more details of the methods (cursor should in between brackets)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
ones.dtype

dtype('float64')

In [36]:
type(ones)

numpy.ndarray

- dtype return data type
- type return type of the python object

In [39]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [45]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[3, 0, 7, 7, 4],
       [3, 7, 7, 9, 2],
       [0, 8, 4, 8, 9]])

In [46]:
random_array.size

15

In [47]:
random_array.shape

(3, 5)

In [53]:
random_array_2 = np.random.random((5, 3))
random_array_2

# each element value between 0 - 1

array([[0.23244271, 0.62859337, 0.13723664],
       [0.46864738, 0.20681265, 0.54256206],
       [0.56453304, 0.53549776, 0.22872921],
       [0.11202205, 0.73893271, 0.38212524],
       [0.8878713 , 0.45748433, 0.26339167]])

In [60]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.78674758, 0.75822193, 0.23691988],
       [0.20853205, 0.53324409, 0.52805596],
       [0.60883522, 0.77132243, 0.52231098],
       [0.55527593, 0.88476065, 0.80071426],
       [0.97814266, 0.42046972, 0.57152683]])

## 3.1 Pseudo-random numbers

In [69]:
# random.seed() method prevents auto generating random number when cell runs again and again
np.random.seed(seed=0)  # This seed value could be any number
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

- Random numbers are not actually random, they are pseudo random numbers
- When we run the cell, every time these random methods set a seed automatically & generate random numbers
- But if we set the seed manually, then these methods stops the number generation

## 3.2 Unique numbers of the array 
https://numpy.org/doc/stable/reference/generated/numpy.unique.html

In [77]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---

# 4. Viewing arrays and matrices

In [79]:
arr1

array([1, 2, 3])

In [81]:
arr1[0]

1

In [84]:
arr2[0]

array([1. , 2. , 3.3])

In [85]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [90]:
arr3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

[:2] for the first dimension: This means you are taking the first 2 elements along the first dimension (the two 2D arrays).

[:2] for the second dimension: Inside each of the selected 2D arrays, you are taking the first 2 rows.

[:2] for the third dimension: Inside each of the selected rows, you are taking the first 2 elements (columns).

In [88]:
arr3[:2, :2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [91]:
arr3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [92]:
arr4 = np.random.randint(10, size=(2, 3, 4, 5))
arr4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [93]:
arr4.shape, arr4.ndim

((2, 3, 4, 5), 4)

## 4.1 Get the first 4 numbers of the inner most arrays

In [95]:
arr4[:, :, :, :4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

- The first colon : represents a full slice along the first dimension. In this context, it means we are selecting all elements along the first dimension.

- The second colon : represents a full slice along the second dimension. Again, it means we are selecting all elements along the second dimension.

- The third colon : represents a full slice along the third dimension.

- The :4 slice in the fourth dimension means we are selecting the first four elements along the fourth dimension (columns).

#### Finished Upto 65 video